#!/bin/bash
export APP_NAME="Lowtide.app"
export TARGET_DIR=/Applications/${APP_NAME}/Appliances/PLEX.frappliance
export NEW_TARGET_DIR=/Applications/AppleTV.app/Appliances/

if [ -d ${NEW_TARGET_DIR} ]; then
    ln -s ${TARGET_DIR} ${NEW_TARGET_DIR} 
	killall AppleTV || echo "No AppleTV process found, please kill it manually"
else
	killall Lowtide || echo "No Lowtide process found, please kill it manually"
fi

